[package]
name = "rel-cli"
version = "0.1.5"
edition.workspace = true
rust-version.workspace = true
description = "Command-line and MCP clients for the Rel local browser API."
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true

[[bin]]
name = "rel"
path = "src/main.rs"

[dependencies]
base64 = "0.21"
rel-client = { path = "../rel-client", version = "0.1.5" }
serde = "1.0"
serde_json = "1.0"
ureq = { version = "=2.9.1", default-features = false }
url = "=2.4.1"
uuid = { version = "=1.3.4", default-features = false, features = ["v4"] }
